import type { Metadata } from "next";
import "@/assets/app.css";
import NavBar from "@/components/NavBar";
import { League_Spartan, Metal, Gloria_Hallelujah } from "next/font/google";
import ContentWidthContainer from "@/components/ContentWidthContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// fonts

const league_spartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-league-spartan",
  display: "swap",
});

const metal = Metal({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-metal",
  display: "swap",
});

const gloria_hallelujah = Gloria_Hallelujah({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gloria-hallelujah",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${league_spartan.variable} ${metal.variable} ${gloria_hallelujah.variable}`}>
      <body className={`antialiased`}>
        <NavBar />
        <ContentWidthContainer>{children}</ContentWidthContainer>
      </body>
    </html>
  );
}
